-- Webhook events table
CREATE TABLE IF NOT EXISTS `webhook_events` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    event VARCHAR(50) NOT NULL,
    resource VARCHAR(255) NOT NULL,
    timestamp BIGINT NOT NULL,
    attempt INT,
    data JSON NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);