// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package persmysql_sqlc_gen

import (
	"encoding/json"
	"time"
)

type WebhookEvent struct {
	ID        int64
	Resource  string
	Event     string
	Timestamp time.Time
	Data      json.RawMessage
}
