version: '3'

tasks:

  go-sqlc-generate:
    cmds:
      - go tool sqlc generate
    dir: pkg/repositories/persistence/persmysql/persmysql_sqlc_src
    generates:
      - pkg/repositories/persistence/persmysql/persmysql_sqlc_gen/*.go
  
  db-up:
    cmds:
      - docker compose --profile db up --force-recreate --detach db
 
  db-down:
    cmds:
      - docker compose --profile db stop db db-setup
      - docker compose --profile db rm --force --volumes db db-setup

  db-inspect:
    cmds:
      - docker compose --profile db run --rm --no-deps db-shell
    interactive: true

  db-reset:
    deps:
      - db-down
    cmds:
      - docker compose --profile db up --force-recreate --detach db
      - docker compose --profile db up --force-recreate --build db-setup
      - docker compose --profile db ps db

  run-dev:
    cmds:
      - docker compose --profile db up --build --force-recreate --no-deps --menu backend
    interactive: true

  run-all:
    deps:
      - db-reset
    cmds:
      - docker compose --profile db up --remove-orphans --force-recreate --build backend

  remote-add-docker-context:
    requires:
      vars:
        - RINGOVER_WEBHOOKS_TEST_SSH_HOST
    cmds:
      - docker context create ringover-webhooks-sdk-test --docker "host=ssh://root@{{.RINGOVER_WEBHOOKS_TEST_SSH_HOST}}"

  remote-up-build-all:
    cmds:
      - docker --context ringover-webhooks-sdk-test compose --profile all down --timeout 0 --remove-orphans --volumes
      - docker --context ringover-webhooks-sdk-test compose --profile db up --force-recreate --build --detach backend

  remote-up-nobuild-all:
    cmds:
      - docker --context ringover-webhooks-sdk-test compose --profile all down --timeout 0 --remove-orphans
      - docker --context ringover-webhooks-sdk-test compose --profile db up --force-recreate --no-build --detach backend

  remote-logs:
    cmds:
      - docker --context ringover-webhooks-sdk-test compose --profile db logs -n 100 -f backend
  
  postman-test:
    cmds:
      - docker compose --profile test --profile db run --rm --no-deps postman-tests
    